---
dotfiles_home: "{{ ansible_env.HOME}}/dotfiles"

# Backup old .gitconfig file
git_gitconfig_backup: yes

# Name used in commit message
git_full_name: ""

# Github username
git_user: ""

# If you use github, the should be the same as the email
git_email: ""

# Add your custom git alias in 'key = value' format
git_aliases: []
